name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # eller din version, t.ex. 23
          distribution: 'adopt'

      # Navigera till den katalog där pom.xml finns
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./backend # Ändra till den mapp där pom.xml finns

      - name: Run Tests
        run: mvn test
        working-directory: ./backend # Samma här
